Постройте мелкие сетки на гридах для подходящих компонентов
htmlacademy-htmlcss/1814593-device-32 pull request #10
Opened 2021-11-19 19:21 UTC by ElenaOldlady

2021-11-20 00:21 UTC, arloktev requested changes

2021-11-20 00:21 UTC, arloktev commented on index.html
> +	<!--
А почему у тебя форма закомментирована? Ее можно в CSS скрыть с помощью display: none;

2021-11-20 00:21 UTC, arloktev commented on index.html
> +						<input class="auth-form-field field" type="text" id="auth-name" name="auth-name" placeholder="Имя Фамилия">
Не будет работать такая связка label с input

2021-11-20 00:21 UTC, arloktev commented on index.html
> +				<form class="auth-form" action="https://echo.htmlacademy.ru/" method="post">
Сама форма откуда-то скопирована, а не с твоего макета)

2021-11-20 00:21 UTC, arloktev commented on index.html
> +				</form>
Нет кнопки отправить

2021-11-20 00:21 UTC, arloktev commented on index.html
> +									fill="#444444" />
вместо цвета нужно указать currentColor, чтобы можно было в CSS переопределять это свойство при взаимодействии

```suggestion
									fill="currentColor" />
```

2021-11-20 00:21 UTC, arloktev commented on index.html
> +					<a class="footer-contacts-phone" href="tel:78128121212">Тел.: +7(812)-812-12-12</a>
```suggestion
					<a class="footer-contacts-phone" href="tel:78128121212">Тел.: +7 (812)-812-12-12</a>
```

2021-11-20 00:21 UTC, arloktev commented on index.html
> +					<button class="newsletter-button" type="а яsubmit">Подписаться</button>
Такого типа не существует

2021-11-20 00:21 UTC, arloktev commented on index.html
> +								</svg>
Эти иконки надо вставить через псевдоэлементы и background

2021-11-20 00:21 UTC, arloktev commented on index.html
>  						<button class="search-button" type="submit"></button>
А тут по макету еще слово есть в кнопке

2021-11-20 00:21 UTC, arloktev commented on image/index.html
> +				<a href="https://htmlacademy.ru/" img="" src="image/htmlacademy" alt="Ссылка на сайт htmlacademy" width="115"
А что это у тебя вообще за файл такой image/index.html?

2021-11-20 00:21 UTC, arloktev commented on css/style.css
> +	margin: 0;
margin-top: 0;

2021-11-20 00:21 UTC, arloktev commented on css/style.css
> +	background-position: center;
Сокращенную форму можно использовать

2021-11-20 00:21 UTC, arloktev commented on css/style.css
> +	height: 580px;
а тут min-height

2021-11-20 00:21 UTC, arloktev commented on css/style.css
> +	width: 920px;
Наверное лучше max-width: 920px; width: 100%;

2021-11-20 00:21 UTC, arloktev commented on css/style.css
> +.htmlacademy-tab:hover {
это же svg, почему tab?) может быть icon хотя бы?

2021-11-20 00:21 UTC, arloktev commented on css/style.css
> +	background-color: #ffffff;
Не надо менять background-color

2021-11-20 00:21 UTC, arloktev commented on css/style.css
>  }
:not(:last-child) { margin-right: 15px }

2021-11-20 00:21 UTC, arloktev commented on css/style.css
> +	letter-spacing: 00.2em;
Лишний ноль или не в том месте...

2021-11-20 00:21 UTC, arloktev commented on css/style.css
> +	width: 760px;
А зачем ширину фиксировано?

2021-11-20 00:21 UTC, arloktev commented on css/style.css
> +	padding-right: 26px;
У тебя кнопки назад/вперед они как бы прижимаются к левому/правому краю, на созвоне показывал

2021-11-20 00:21 UTC, arloktev commented on css/style.css
> +	width: 760px;
А чем тебя не устроило width: 100%?

2021-11-20 00:21 UTC, arloktev commented on css/style.css
> +	left: 72px;
Должно быть top: 50%; left: 50%; transform: translate(-50%, -50%) и это ссылка лежать в обертку изображения, чтобы всегда была по центру в независимости от заголовка карточки

2021-11-20 00:21 UTC, arloktev commented on css/style.css
> -	background: url("../image/compare.svg") no-repeat;
Зря наоборот должно быть через псевдоэлемент, так как меняется прозрачность

2021-11-20 00:21 UTC, arloktev commented on catalog.html
> +					<button class="filter-button btn-link btn-link-show" type="submit">Показать</button>
а зачем btn-link-show? какие-то индивидуальные стили для этой кнопки? а зачем тогда filter-button?

2021-11-20 12:43 UTC, ElenaOldlady commented on css/style.css
> +	width: 760px;
когда я делаю width: 100% у меня кнопка улетает за пределы границ, поэтому я оставила width: 760px

2021-11-21 05:30 UTC, arloktev requested changes

2021-11-21 05:30 UTC, arloktev commented on index.html
> +              </button>
Кнопки у тебя должны быть одни на весь слайдер

2021-11-21 05:30 UTC, arloktev commented on index.html
> +              </div>
Также и с пагинацией

2021-11-21 05:30 UTC, arloktev commented on css/style.css
> +  background: #EBEBEB;
background-color

2021-11-21 05:30 UTC, arloktev commented on css/style.css
> +  border: 5px solid #AF4FFF;
По стайлгайду надо будет отдельно проверить везде, так как когда ты сразу добавляешь border у тебя контент будет прыгать и так не примут, если задаешь border при фокусе/ховере, то в обычном состоянии этот border тоже должен присутствовать, только с transparent цветом

2021-11-21 05:30 UTC, arloktev commented on image/professional-mini.svg
> +<image id="image0_3_661" width="360" height="380" xlink:href="data:image/jpeg;base64,/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP/sABFEdWNreQABAAQAAABkAAD/4QOLaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLwA8P3hwYW
Если такое изображение в SVG, то значит ты неправильно выбрала формат изображений

2021-11-21 05:30 UTC, arloktev commented on image/recreational-mini.svg
> +<image id="image0_24_261" width="360" height="380" xlink:href="data:image/jpeg;base64,/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP/sABFEdWNreQABAAQAAABkAAD/4QOLaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLwA8P3hwY
Аналогично

2021-11-21 05:30 UTC, arloktev commented on css/style.css
> +/*
А почему закомментировано? Ты этот код сама написала или скопировала из демок?

2021-11-21 05:30 UTC, arloktev commented on css/style.css
> +  border-radius: 1px;
border-radius добавляется только при фокусе?

2021-11-21 05:30 UTC, arloktev commented on css/style.css
> +  border-bottom: 2px solid #FFC700;
Можно объединить через запятую селекторы с одинаковыми стилями

2021-11-21 05:30 UTC, merged

2021-11-21 14:47 UTC, ElenaOldlady commented on css/style.css
> +	padding-right: 26px;
они у меня прибиты к левому/правому краю