Сетка страницы и крупных блоков на флексах для страницы каталога
htmlacademy-htmlcss/1814593-device-32 pull request #8
Opened 2021-11-01 21:59 UTC by ElenaOldlady

2021-11-02 19:27 UTC, arloktev requested changes

2021-11-02 19:27 UTC, arloktev commented on css/style.css
> +	justify-content: space-between;
А зачем тут space-between?

2021-11-02 19:27 UTC, arloktev commented on catalog.html
> +			<div class="container">
Я бы на этой странице контейнер сделал один на весь main

2021-11-02 19:27 UTC, arloktev commented on catalog.html
> +				<h2 class="inner-header-title"> Каталог</h2>
Нам этот тег не нужен

2021-11-02 19:27 UTC, arloktev commented on catalog.html
> +		<section class="inner-header">
На мой взгляд лишняя обертка

2021-11-02 19:27 UTC, arloktev commented on css/style.css
> +	padding-left: 200px;
Без отступа слева

2021-11-02 19:27 UTC, arloktev commented on css/style.css
> +}
Не понятные стили какие-то...зачем они?

2021-11-02 19:27 UTC, arloktev commented on css/style.css
> +	width: 800;
Не сработает

2021-11-02 19:27 UTC, arloktev commented on css/style.css
> +	padding-left: 540px;
Лишнее

2021-11-02 19:27 UTC, arloktev commented on css/style.css
> +}
Лучше на родителя flex

2021-11-02 21:16 UTC, ElenaOldlady commented on css/style.css
> +	padding-left: 200px;
не знаю почему у тебя тут два пробела, у меня пробела нет

2021-11-03 11:57 UTC, ElenaOldlady commented on catalog.html
> +				<h2 class="inner-header-title"> Каталог</h2>
не поняла...

2021-11-03 11:58 UTC, ElenaOldlady commented on catalog.html
> +		<section class="inner-header">
ты про section? почему лишняя?

2021-11-03 11:59 UTC, ElenaOldlady commented on css/style.css
> +	width: 800;
почему?

2021-11-03 12:00 UTC, ElenaOldlady commented on css/style.css
> +	width: 800;
что не так?

2021-11-10 16:04 UTC, arloktev commented on index.html
> +				<a href="https://htmlacademy.ru/" img="" src="image/htmlacademy" alt="Ссылка на сайт htmlacademy"
У ссылки не бывает таких аттрибутов)

2021-11-10 16:09 UTC, arloktev commented on css/style.css
> +	flex-direction: row;
row по умолчанию у flex-direction

2021-11-10 16:11 UTC, arloktev commented on css/style.css
> +	text-align: start;
А разве не по умолчанию выравнивание слева?

2021-11-10 16:11 UTC, arloktev commented on css/style.css
> +	flex-direction: row;
По умолчанию, почисти дальше по коду

2021-11-10 16:12 UTC, arloktev commented on css/style.css
> +	width: 497px;
Ширину надо ограничивать у родителя

2021-11-10 16:14 UTC, arloktev commented on css/style.css
> +	width: 800px;
flex-grow: 1;

2021-11-10 16:16 UTC, arloktev commented on css/style.css
> +	margin-left: 200px;
А зачем этот отступ?

2021-11-10 16:16 UTC, arloktev commented on css/style.css
> +	width: 236px;
Разве по макету ширина не больше?

2021-11-10 16:16 UTC, arloktev commented on css/style.css
> +	grid-template-columns: 360px 360px;
repeat, 1fr

2021-11-10 16:16 UTC, arloktev commented on css/style.css
> +	margin: 0;
если обнуляешь только margin-top этой строкой, то лучше написать margin-top: 0;

2021-11-10 16:17 UTC, arloktev commented on css/style.css
>  }
Дублирование кода, следовательно надо придумать общий класс

2021-11-10 16:18 UTC, arloktev commented on css/style.css
>  }
А тут у тебя меняется только цвет), соответственно дополнительный класс должен отвечать только за цвет

2021-11-13 07:49 UTC, arloktev requested changes

2021-11-13 07:49 UTC, arloktev commented on index.html
> +						<form class="navigation-form" action="#" method="post">
Я бы вытащил данную форму из ul

2021-11-13 07:49 UTC, arloktev commented on index.html
> +			<img class="logo" src="image/deviceheader.svg" alt="логотип device" width="145" heigth="36">
У тебя опечатка в height, можно такие ошибки обнаружить на этапе проверки валидатором https://validator.w3.org/#validate_by_input

2021-11-13 07:49 UTC, arloktev commented on index.html
> +						<a class="navigation-link navigetion-plus" href="/catalog.html">Каталог товаров</a>
При публикации на github-pages https://htmlacademy-htmlcss.github.io/1814593-device-32/8/ при клике на данный пункт у меня 404 страница, надо удалить /
Опечатка в слове navigation

2021-11-13 07:49 UTC, arloktev commented on index.html
> +							<p class="slider-text description">Этот обычный, на первый взгляд, квадрокоптер оснащён мощным лазером,
А зачем тебе второй класс description?

2021-11-13 07:49 UTC, arloktev commented on index.html
> +								<div class="distance-radius">
Класс должен быть без привязки к обозначению, а то тут у тебя дальность полета, а  в классе написано радиус

2021-11-13 07:49 UTC, arloktev commented on index.html
> +							<div class="category-item-text">
А зачем лишний div наверное можно обойтись p

2021-11-13 07:49 UTC, arloktev commented on index.html
> +							<div class="category-item-image">
На такие обертки можно применять слово wrapper, и класс будет что-то типа category-img-wrapper

2021-11-13 07:49 UTC, arloktev commented on index.html
> +					<div class="delivery-tab">
А нужен ли дополнительный div, можно наверное и без него обойтись?

2021-11-13 07:49 UTC, arloktev commented on index.html
> +							<li class="delivery-item"> <a href="#">Доставка</a> </li>
Если на один элемент добавила класс, то нужно продублировать и для других элементов (например, бекендер будет потом интегрировать твою верстку и ему придется делать дополнительные условия)

2021-11-13 07:49 UTC, arloktev commented on index.html
> +							<li> <a href="#">Кредит</ass=>
А причем тут задница? 😂

2021-11-13 07:49 UTC, arloktev commented on index.html
> +							<li> <a href="#">Гарантия</a> </liss=>
Ошибка

2021-11-13 07:49 UTC, arloktev commented on index.html
> +								<img src="image/delivery2.svg" alt="Доставка" width="136" height="164">
Это какое изображение? Контентное или декоративное?

2021-11-13 07:49 UTC, arloktev commented on index.html
> +						<img class="rareproduct-image" src="/image/rareproduct.svg" alt="Доставка редких товаров" width="47"
Это какое изображение?

2021-11-13 07:49 UTC, arloktev commented on index.html
> +						акции, спецпредложения и вот это вот всё.</p>
Нужно удалить лишние переносы на новую строку

2021-11-13 07:49 UTC, arloktev commented on index.html
> +					<input class="button" type="text" name="sign" id="sign" placeholder="Ваш e-mail">
Не исправила

2021-11-13 07:49 UTC, arloktev commented on catalog.html
> +					</li>
Это наверное вынести бы в отдельный ul

2021-11-13 07:49 UTC, arloktev commented on catalog.html
> +						<a class="breadcrumbs-list" href="/index.html">Главная</a>
это ссылка, класс не подходящий

2021-11-13 07:49 UTC, arloktev commented on catalog.html
> +						<a class="breadcrumbs-list" href="/catalog.html">Каталог товаров</a>
Надо удалить слеш в урле

2021-11-13 07:49 UTC, arloktev commented on catalog.html
> +										<span class="colour-span"></span>
А в каких целях ты хочешь использовать этот элемент?

2021-11-13 07:49 UTC, arloktev commented on catalog.html
> +										<input class="visually-hidden colour-input" type="checkbox" name="catalog" value="black">
наверное colour более подходящий name для инпута

2021-11-13 07:49 UTC, arloktev commented on catalog.html
> +									<label class="bluetooth">
Опять же не даем названия классов с привязкой к обозначению, у нас могут быть стилистически также оформлены инпуты обозначающие, например, "В наличие"

2021-11-13 07:49 UTC, arloktev commented on catalog.html
> +										<input class="visually-hidden bluetooth-input" type="radio" name="function">
Неправильный name

2021-11-13 07:49 UTC, arloktev commented on catalog.html
> +					<button class="visually-hidder" type="submit">Отсортировать продукт</button>
опечатка в классе

2021-11-13 07:49 UTC, arloktev commented on catalog.html
> +						<a class="pagination-link pagination-current" href="#">1</a>
А что у тебя все ссылки активны (я про pagination-current)?

2021-11-13 07:49 UTC, arloktev commented on catalog.html
> +							<span class="pagination-span">Вперед</span>
Класс должен быть без привязки к тегу

2021-11-13 07:49 UTC, arloktev commented on css/style.css
> +	width: 1160px;
Не, до этого было правильно с max-width: 1160px; width: 100% почему решила переделать?
Если ты задаешь жестко значение в px, то при уменьшении экрана у тебя контейнер так и останется 1160px и появится горизонтальный скролл, а если как я выше писал - укажешь, то он подстроится под экран устройства

2021-11-13 07:49 UTC, arloktev commented on css/style.css
> +	padding: 0;
Отступы по краям обычно ставят padding-right: 15px; padding-left: 15px;
чтобы при разрешении в ширину контейнера не прилипал контент к краям устройства

2021-11-13 07:49 UTC, arloktev commented on css/style.css
> +	margin: 0;
А зачем обнулила все отступы?

2021-11-13 07:49 UTC, arloktev commented on css/style.css
> +	box-shadow: 0 -137px 0 0 white;
можно использовать свойство inset и наверное эти стили вешать прям на header

2021-11-13 07:49 UTC, arloktev commented on css/style.css
> +	margin: 0;
Я за то, чтобы обнулять только те стили, которые заданы

2021-11-13 07:49 UTC, arloktev commented on css/style.css
> +	background: url("/image/search.svg") no-repeat;
Надо путь задать относительно той директории, в которой находишься и так для всех изображений

2021-11-13 07:49 UTC, arloktev commented on css/style.css
>  }
А зачем?

2021-11-13 07:49 UTC, arloktev commented on css/style.css
> +	background: url("/image/vectoryellow.png") repeat-x 0 50%;
У тебя полоска по стайлгайду изменяется, да и вообще такие декоративные штуки, если можно, то лучше делать через CSS (в твоем случае через before)

2021-11-13 07:49 UTC, arloktev commented on css/style.css
>  }
Если повторяются стили, то это повод задумать и сделать один общий класс, например, slider-button
А уже индивидуальные стили добавить на дополнительные классы

2021-11-13 07:49 UTC, arloktev commented on css/style.css
> +	margin: 0;
Зачем обнулять, а потом снизу задавать стили?

2021-11-13 07:49 UTC, arloktev commented on css/style.css
> +	outline-offset: -2px;
Это наверное не нужно

2021-11-13 07:49 UTC, arloktev commented on css/style.css
> +	width: 500px;
А через проценты не получится?

2021-11-13 07:49 UTC, arloktev commented on css/style.css
> +	background: url("/image/vectorblack.png") no-repeat top left;
Полоска относится к заголовку, соответственно ее нужно делать у нее

2021-11-13 07:49 UTC, arloktev commented on css/style.css
> +	background: url("/image/vectoryellow.png") repeat-x 0 50%;
Если видишь одинаковые стили, то можно их определить один раз и использовать этот класс для реализации какой-то стилизации

2021-11-13 07:49 UTC, merged